apiVersion: apps/v1 
kind: Deployment
metadata:
  name: reuters-model-deployment
spec:
  replicas: 3
  selector:
        matchLabels:
            app: reuters-model-server
  template:
    metadata:
      labels:
        app: reuters-model-server
    spec:
      containers:
      - name: reuters-model-container
        image: msmolyak/reuters_model:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: reuters-model-service
  name: reuters-model-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: reuters-model-server
