vscode:
    extensions:
        - vscjava.vscode-java-pack
        - redhat.fabric8-analytics
        - ms-azuretools.vscode-docker
        - vscjava.vscode-java-debug
        - vscjava.vscode-java-dependency
        - vscjava.vscode-java-test
        - vscjava.vscode-maven
